const USER_SIGNIN = 'USER_SIGNIN';
const USER_SIGNOUT = 'USER_SIGNOUT';
const SET_CONTENTS = 'SET_CONTENTS';
const SET_MY_LIST = 'SET_MY_LIST';
const ADD_CONTENT_TO_MY_LIST = 'ADD_CONTENT_TO_MY_LIST';
const REMOVE_CONTENT_FROM_MY_LIST = 'REMOVE_CONTENT_FROM_MY_LIST';
const SAVE_MY_LIST_IN_DB = 'SAVE_MY_LIST_IN_DB';

export {
    USER_SIGNIN,
    USER_SIGNOUT,
    SET_CONTENTS,
    SET_MY_LIST,
    ADD_CONTENT_TO_MY_LIST,
    REMOVE_CONTENT_FROM_MY_LIST,
    SAVE_MY_LIST_IN_DB
}