const USER_SIGNIN = 'USER_SIGNIN';
const USER_SIGNOUT = 'USER_SIGNOUT';
const SET_CONTENTS = 'SET_CONTENTS';
const SET_MY_CONTENTS = 'SET_MY_CONTENTS';

export {
    USER_SIGNIN,
    USER_SIGNOUT,
    SET_CONTENTS,
    SET_MY_CONTENTS
}